# https://github.com/andresz1/size-limit-action

name: Size Limit

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: andresz1/size-limit-action@v1.2.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
